target ‘Qichegou’ do

pod ‘AFNetworking’
pod ’Masonry’
pod 'MJRefresh', '~> 3.1.9'
pod 'SDWebImage', '~> 3.8.1'
pod 'ReactiveCocoa', '~> 2.5'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'IQKeyboardManager', '~> 4.0.4'

end